### ISSUE TITLE
Support automatic colorization via `<rgb>` tags

### ISSUE THREAD

**Issue by slurps-mad-rips** [ixm-one/ixm#11]
Currently, we provide a small set of 4-bit colors for foreground printing. There is, honestly, no reason people cannot have a custom RGB colorization. Taking a page from the python `pastel` package, we'll have the builtin `print()` function perform automatic colorization via special `<rgb>text</rgb>` tags. The actual syntax for how to get high intensity colors and such needs to be decided upon, but preliminary tests show that this *should* be a simple "find-replace" with CMake regex, as awful as that regex implementation might be. :)

**Comment by ThePhD** [comment]
🎉
