### ISSUE TITLE
Automatic generation of CMake exports

### ISSUE THREAD

**Issue by akalsi87** [ixm-one/ixm#12]
# Feature Request

***

Since I can't open an issue to ask a question, I had to classify it as an enhancement.

It would be awesome to not have to write by hand an export file for CMake libraries. The information is already provided in the CMakeLists.txt and a common pattern is to then go repeat the dependencies in the exports file.

## What is the current behavior?

Unsure if it exists.

***

## Why should this be changed or added?

Because it removes useless repetition.

***

## How would you implement this?

By introspecting the properties of the targets defined under a project.

***

## Additional Information

**Are you willing to work on this yourself?** Yes
**How urgent is it to have this feature?** Not urgent.
**Is this feature request possibly out of scope for IXM?** Not sure.

**Comment by slurps-mad-rips** [comment]
Hello! This is planned as part of the Coven blueprint. Because IXM is still not even in alpha, different parts are focused on. I've had to take a break the last few weeks due to personal life stuff, while also working on the design of the documentation. I also have a local, (but not yet uploaded to github) list of  issues that are required for the alpha release. :)

**Comment by akalsi87** [comment]
Thanks. I don't want to take up too much of your time but I was wondering why (atleast the Brujeria blueprint) is opposed to superprojects? It seems to assume the project itself is a single target. Is that a temporary state of the project? If so, I'll refrain from more questions. :)

**Comment by slurps-mad-rips** [comment]
Brujeria is supposed to be used in conjunction with the [brujeria python library](https://github.com/slurps-mad-rips/brujeria). In that instance, you treat each directory as a python module itself, and thus need an init.cmake. All of this integration is a bit of a ways off while I finish up some of the inner workings of IXM (Such as fixing unity builds, PCH generation, etc.)

**Comment by bruxisma** [comment]
Closing, as this project has burned me out, and I cannot continue working on it in its current state. CMake has changed massively since this project was started. Most of it is no longer necessary. A new repository will be launched in September.
