### ISSUE TITLE
`define_property` override is still needed

### ISSUE THREAD

**Issue by bruxisma** [ixm-one/ixm#22]
Due to the recent removal of the experimental `property` command (which wasn't even implemented), we are still in need of a custom `define_property` to

1) Keep track of defined properties (for the `target_copy_properties` command)
2) Make defining properties *much* easier
3) Allowing us to write *some* documentation in the source code before it is added to the documentation repository.

**Comment by slurps-mad-rips** [comment]
I'm iffy on whether this should still go into IXM. On the one hand we can keep track of custom properties. On the other hand we end up with scripts that just call `define_property` and that's time wasted when running the configure stage. :/

**Comment by bruxisma** [comment]
Closing, as this project has burned me out, and I cannot continue working on it in its current state. CMake has changed massively since this project was started. Most of it is no longer necessary. A new repository will be launched in September.
