### ISSUE TITLE
Please consider replacing/amending/replacing the Code of Conduct

### ISSUE THREAD

**Issue by eyalroz** [ixm-one/ixm#38]
Hello ixm-one,

I recently noticed this interesting repository. However, I noted in particular that you have chosen to adopt a highly repressive Code-of-Conduct, in the sense that it mandates secret trials of contributors based on anonymous complaints, with no due process rights in such proceedings.

Now, I realize this is a one-person repository, so the whole scenario I described is moot. But that is also a reason why removing, replacing or amending the CoC document is super easy and does not require any organizational adjustment.

**Comment by slurps-mad-rips** [comment]
No.
