### ISSUE TITLE
Support AppImage where possible

### ISSUE THREAD

**Issue by bruxisma** [ixm-one/ixm#5]
[AppImage][1] is a pretty incredible tool and makes distribution of applications an absolute breeze compared to other forms of installation. However, CPack does not support generating an AppImage as a packaging format. It should! And it's doable. 

[1]: https://appimage.org/

**Comment by Milerius** [comment]
I handle it in my projects if you want i can link it to you

**Comment by Milerius** [comment]
It's was something like:

```CMake
 if (AUTO_BUILD_APPIMAGE)
        add_custom_command(TARGET nephtys_client
                POST_BUILD COMMAND
                bash -c
                "VERSION=${PROJECT_VERSION} ${PROJECT_SOURCE_DIR}/tools/linux/linuxdeploy-x86_64.AppImage --appdir ${nephtys_client_runtime_directory}/NephtysClientAppDir --output appimage"
                $<TARGET_FILE:nephtys_client>
                WORKING_DIRECTORY ${nephtys_client_runtime_directory})
    endif ()
```

**Comment by bruxisma** [comment]
Closing, as this project has burned me out, and I cannot continue working on it in its current state. CMake has changed massively since this project was started. Most of it is no longer necessary. A new repository will be launched in September.
