### ISSUE TITLE
Add FindSDL2.cmake

### ISSUE THREAD

**Issue by slurps-mad-rips** [ixm-one/ixm#8]
SDL2 is a lovely library, but the default `FindSDL2.cmake` files that are out there leave a lot to be desired. There's no reason we can't provide a file to help people along the way. It should also provide support for finding the various SDL2 components, such as TTF, image, net, mixer, etc.

**Comment by slurps-mad-rips** [comment]
Progress has been made on this for the alpha release.

Small changes to `find(LIBRARY)` are needed, but will be handled soon.

**Comment by slurps-mad-rips** [comment]
We have this now, however, I'm also doing work with the current SDL2 CMake files to make the actual CMake building experience "not a nightmare". At some point, if we're lucky, we don't need the FindSDL2.cmake file!

**Comment by ThePhD** [comment]
Nice.
