### ISSUE TITLE
Support compiling tools via a separate host toolchain

### ISSUE THREAD

**Issue by bruxisma** [ixm-one/ixm#9]
Currently, when CMake is cross compiling, it sets `CMAKE_CROSS_COMPILING` to `TRUE`. This also ends up meaning we can't compile any tools for code generation or otherwise when cross compiling. This is a huge limitation. However, there is a workaround and we can wrap it up into a special `add_tool()` command.

This command will perform the following steps when `CMAKE_CROSS_COMPILING` is `ON`

 * Get the current list of enabled languages.
 * For each language we 
   * `unset()` certain variables in the current *function* scope.
   * `set()` the current `CMAKE_SYSTEM_NAME` into a temporary variable
   * `set()` the `CMAKE_HOST_SYSTEM_NAME` to `CMAKE_SYSTEM_NAME`
   * `set(CMAKE_PLATFORM_INFO_DIR)` to some predetermined directory
   * `include(CMakeDetermine<LANG>Compiler)`
   * `include(${CMAKE_PLATFORM_INFO_DIR}/CMake<LANG>Compiler.cmake)
   * `set()` host versions of variables
   * Set variables onto a `dict()` and save to disk with some sort of hash
* Call `try_compile(PROJECT)` with flags that are stored in said `dict()` (We cannot use generator expressions 😞). The project can either be the current one, or a separate one altogether.
* Call `add_executable(name IMPORTED)` and set the path to the given target.

The above is just the tip of the iceberg. There are many MANY things that need to be taken into account, such as, but not limited to:
 * FetchContent locations
 * System Dependencies
 * Variables set by toolchain files

This is going to be a big feature, but it is EXTREMELY useful. That said, it's low priority until everything else is stable.

**Comment by slurps-mad-rips** [comment]
One thing we should consider is possibly having this be a flag on `add_executable()`, such as `add_executable(TOOL)`

One other major question I have is should this be done during the CONFIGURE step, or as a POST-CONFIGURE step? I'm leaning towards the latter. No matter what we do, we *can't* have it happen during the build itself. CMake just doesn't work that way 😞

I should note however that this question of *when* to execute is only when we are cross compiling. If we aren't cross compiling, then the tool is built during the BUILD stage.

**Comment by slurps-mad-rips** [comment]
Some work is being done in this area, but it's not going to be pretty. If anything it's going to be a terrible hack. Effectively, we run CMake with whatever flags you want (via `try_compile`, rather than `execute_process`). We specifically run the `install` target to a special directory under `CMAKE_BINARY_DIR`. Once that's done, we prepend the sysroot of the install to this special directory. That's all we're going to do. This directory will most likely be a hash of some parameters passed to the command along with some additional environment level settings. It will be fragile and barely work.... Like most things in CMake 😞

**Comment by bruxisma** [comment]
Closing, as this project has burned me out, and I cannot continue working on it in its current state. CMake has changed massively since this project was started. Most of it is no longer necessary. A new repository will be launched in September.
